defaults:
  - meta_base


backbone:
  _target_: backbones.resnet.ResNet12
  layer_dim: [ 64, 64 ]

cls:
  _target_: methods.metaoptnet_b.MetaOptNet
  num_classes: ${train_classes}
  num_features: 64


name: metaoptnet